Add Batch Predict to Documentation
ucbrise/clipper-website pull request #21
Opened 2018-08-03 12:33 UTC by simon-mo

Add batch predict to:
1. tutorials
2. api doc

Update api doc to 0.3.0

![image](https://user-images.githubusercontent.com/21118851/43642697-e3cdbf30-9728-11e8-92b4-f0e96d441270.png)

![image](https://user-images.githubusercontent.com/21118851/43643022-07ec5790-972a-11e8-8d61-4d5aa9279ce3.png)

![image](https://user-images.githubusercontent.com/21118851/43643024-0a9f9664-972a-11e8-936c-702b4b875b12.png)

2018-08-03 12:35 UTC, simon-mo commented
Resolves https://github.com/ucbrise/clipper/issues/544

2018-08-03 16:17 UTC, RehanSD commented on content/tutorials/batch_predict.md
> +Since release 0.3.0, Clipper has a batch prediction inferface for query. Instead of sending:
inferface -> interface

2018-08-03 16:19 UTC, RehanSD requested changes

2018-08-03 16:19 UTC, RehanSD commented on content/tutorials/batch_predict.md
> +Since release 0.3.0, Clipper has a batch prediction inferface for query. Instead of sending:
inferface -> interface

2018-08-03 16:19 UTC, RehanSD commented on content/tutorials/batch_predict.md
> +Clipper will return prediction for the batch in the original order.
prediction*s*

2018-08-03 16:19 UTC, RehanSD commented on content/tutorials/batch_predict.md
> +If a request contain both `input` and `input_batch`, `input` will take precedence and `input_batch` will be ignored.
contain*s*

2018-08-03 16:19 UTC, RehanSD commented on content/tutorials/r-deployment.md
> +You can install rclipper package by cloning Clipper repository
install *the* rclipper package

2018-08-03 16:19 UTC, RehanSD commented on content/tutorials/r-deployment.md
> +You can install rclipper package by cloning Clipper repository
cloning *the* Clipper repository

2018-08-03 16:19 UTC, RehanSD commented on content/tutorials/r-deployment.md
> +and run `R CMD INSTALL`:
run*ning*

2018-08-03 16:23 UTC, RehanSD commented on content/tutorials/batch_predict.md
> +Since release 0.3.0, Clipper has a batch prediction inferface for query. Instead of sending:
Starting

2019-06-07 16:50 UTC, covix commented
I just spent a few hours trying to understand how the batch predictions works (together with some strange query behaviour regarding the `input` parameter).

I believe that having the doc updated could help people.
Is this ok to be merged? If not, can I do something to help?

2019-06-07 21:37 UTC, rkooo567 commented
@simon-mo Can I have an access to clipper-websites? Also, what do you think about @covix's comment? I am not sure why this PR is not merged? 

@covix I will get back to you within a few days to answer about your question!

2019-06-15 18:47 UTC, rkooo567 commented
@covix I haven't heard back from @simon-mo. I think it is okay to create a new PR for this. We will appreciate your contribution!

2020-08-20 22:37 UTC, closed without merging